// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TurnosApi.Data;

#nullable disable

namespace TurnosApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312164023_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TurnosApi.Entities.Categoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_nombre");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("TurnosApi.Entities.Paciente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dni");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_pacientes");

                    b.HasIndex("Dni")
                        .IsUnique()
                        .HasDatabaseName("ix_pacientes_dni");

                    b.ToTable("pacientes", (string)null);
                });

            modelBuilder.Entity("TurnosApi.Entities.Profesional", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("matricula");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_profesionales");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_profesionales_categoria_id");

                    b.HasIndex("Matricula")
                        .IsUnique()
                        .HasDatabaseName("ix_profesionales_matricula");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_profesionales_usuario_id");

                    b.ToTable("profesionales", (string)null);
                });

            modelBuilder.Entity("TurnosApi.Entities.Turno", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CanceladoAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelado_at");

                    b.Property<long?>("CanceladoPorId")
                        .HasColumnType("bigint")
                        .HasColumnName("cancelado_por_id");

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint")
                        .HasColumnName("categoria_id");

                    b.Property<long?>("CreadoPorId")
                        .HasColumnType("bigint")
                        .HasColumnName("creado_por_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DescripcionProblema")
                        .HasColumnType("text")
                        .HasColumnName("descripcion_problema");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("paciente_id");

                    b.Property<long>("ProfesionalId")
                        .HasColumnType("bigint")
                        .HasColumnName("profesional_id");

                    b.HasKey("Id")
                        .HasName("pk_turnos");

                    b.HasIndex("CanceladoPorId")
                        .HasDatabaseName("ix_turnos_cancelado_por_id");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_turnos_categoria_id");

                    b.HasIndex("CreadoPorId")
                        .HasDatabaseName("ix_turnos_creado_por_id");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("ix_turnos_paciente_id");

                    b.HasIndex("ProfesionalId", "FechaHora")
                        .IsUnique()
                        .HasDatabaseName("uq_profesional_fecha_hora");

                    b.ToTable("turnos", (string)null);
                });

            modelBuilder.Entity("TurnosApi.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_username");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("TurnosApi.Entities.Profesional", b =>
                {
                    b.HasOne("TurnosApi.Entities.Categoria", "Categoria")
                        .WithMany("Profesionales")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_profesionales_categorias_categoria_id");

                    b.HasOne("TurnosApi.Entities.Usuario", "Usuario")
                        .WithOne("Profesional")
                        .HasForeignKey("TurnosApi.Entities.Profesional", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_profesionales_usuarios_usuario_id");

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TurnosApi.Entities.Turno", b =>
                {
                    b.HasOne("TurnosApi.Entities.Usuario", "CanceladoPor")
                        .WithMany()
                        .HasForeignKey("CanceladoPorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_turnos_usuarios_cancelado_por_id");

                    b.HasOne("TurnosApi.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_turnos_categorias_categoria_id");

                    b.HasOne("TurnosApi.Entities.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_turnos_usuarios_creado_por_id");

                    b.HasOne("TurnosApi.Entities.Paciente", "Paciente")
                        .WithMany("Turnos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_turnos_pacientes_paciente_id");

                    b.HasOne("TurnosApi.Entities.Profesional", "Profesional")
                        .WithMany("Turnos")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_turnos_profesionales_profesional_id");

                    b.Navigation("CanceladoPor");

                    b.Navigation("Categoria");

                    b.Navigation("CreadoPor");

                    b.Navigation("Paciente");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("TurnosApi.Entities.Categoria", b =>
                {
                    b.Navigation("Profesionales");
                });

            modelBuilder.Entity("TurnosApi.Entities.Paciente", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("TurnosApi.Entities.Profesional", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("TurnosApi.Entities.Usuario", b =>
                {
                    b.Navigation("Profesional");
                });
#pragma warning restore 612, 618
        }
    }
}
